---
# Automated setup of a Beowulf AI Cluster.

- name: Set up llama.cpp.
  ansible.builtin.import_playbook: plays/llama_cpp.yml
  tags: ['llama-setup']

- name: Set up distributed-llama.
  ansible.builtin.import_playbook: plays/distributed_llama.yml
  tags: ['distributed-llama-setup']

- name: Set up Exo.
  ansible.builtin.import_playbook: plays/exo.yml
  tags: ['never', 'exo-setup']

- name: Run llama.cpp individual node benchmark.
  ansible.builtin.import_playbook: plays/llama_cpp-benchmark-individual.yml
  tags: ['never', 'llama-bench']

- name: Run llama.cpp benchmark across the full cluster.
  ansible.builtin.import_playbook: plays/llama_cpp-benchmark-cluster.yml
  tags: ['never', 'llama-bench-cluster']
