---
- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600
  become: true

- name: Install dependencies.
  ansible.builtin.package:
    name:
      - git
      - build-essential
      - g++
      - cmake
      - nvtop
      # For Exo.
      - python3-pip
      - python3-dev
      - libdrm-dev
    state: present
  become: true
