---
- name: Set up distributed-llama.
  hosts: cluster
  become: false

  vars_files: ['../config.yml']

  tasks:
    - ansible.builtin.include_tasks: ../dependencies/rhel-based.yml
      when: ansible_os_family == 'RedHat'

    - ansible.builtin.include_tasks: ../dependencies/debian-based.yml
      when: ansible_os_family == 'Debian'

    - name: Ensure working directory exists.
      ansible.builtin.file:
        path: "{{ working_dir }}"
        state: directory
      become: true

    - name: Clone distributed-llama.
      ansible.builtin.git:
        repo: "{{ dllama_source }}"
        dest: "{{ working_dir }}/distributed-llama"
        version: "{{ dllama_version }}"
      become: true

    - name: Fix sgemm.cpp SSE/AVX include guard
      ansible.builtin.replace:
        path: "{{ working_dir }}/distributed-llama/src/nn/llamafile/sgemm.cpp"
        regexp: '^#elif defined\(__AVX2__\)$'
        replace: '#elif defined(__SSE__) || defined(__AVX__) || defined(__AVX2__) || defined(__AVX512F__)'
        backup: yes
      become: true

    - name: Build distributed-llama.
      community.general.make:
        chdir: "{{ working_dir }}/distributed-llama"
        target: "{{ item }}"
      environment: "{{ dllama_build_environment }}"
      become: true
      loop:
        - dllama
        - dllama-api
